# Generated by Django 2.1.5 on 2019-02-04 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
            ],
            options={
                'verbose_name': 'Analyse Result',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100)),
                ('img_desc', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added')),
            ],
            options={
                'verbose_name': 'Image Reference',
                'ordering': ['img_name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAnalyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.TextField(default='Default client infos', null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('results', models.ManyToManyField(to='pi_im.AnalyseResults')),
            ],
            options={
                'verbose_name': 'Analyse Infos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='analyseresults',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi_im.ReferenceImg'),
        ),
    ]
